version: '5'

volumes:
  pgvector_data:

networks:
  ai_implementation_network:
    driver: bridge

services:
  postgres:
    image: ankane/pgvector
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - ai_implementation_network

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    command: 'uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload'
    ports:
      - "8000:8000"
      - "4444:4444"
    volumes:
      - .:/herobot
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}"
    networks:
      - ai_implementation_network
